services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    networks:
      - npm-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    networks:
      - npm-network
networks:
  npm-network:
    external: true
